### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by wenjie2wang** [zoushucai/journalabbr#1]
I came across this package by searching "bibtex" on CRAN and I found some minor issues when trying to figure out what this package does. 

- In the `README.md`, `devtools::install_github("zhoushucai/journalabbr")` contains an extra `h` in `zhou` and should be `devtools::install_github("zoushucai/journalabbr")`.
- It seems that there is no actual data for the `abbrTable` object.  Running `data(abbrTable, package = "journalabbr")` gave me nothing.

**Comment by zoushucai** [comment]
> I came across this package by searching "bibtex" on CRAN and I found some minor issues when trying to figure out what this package does.
> 
> * In the `README.md`, `devtools::install_github("zhoushucai/journalabbr")` contains an extra `h` in `zhou` and should be `devtools::install_github("zoushucai/journalabbr")`.
> * It seems that there is no actual data for the `abbrTable` object.  Running `data(abbrTable, package = "journalabbr")` gave me nothing.

 thank you,  ` abbrTable` is a built-in data set. If you want to view it, clone the  repository, enter the package and load the `R/sysdata.rda` file

**Comment by zoushucai** [comment]
I submitted a new version v0.2.3,  you can try it.
```R
devtools::install_github("zoushucai/journalabbr")
library(journalabbr)
data(abbrTable, package = "journalabbr")
head(abbrTable)


```
