### ISSUE TITLE
Feature request: add option to allow user to supply custom journal abbreviations?

### ISSUE THREAD

**Issue by rmgpanw** [zoushucai/journalabbr#2]
Hi,

Thanks for creating this package. I've just tried it out - found it easy to use and very useful!

There were a few journals which were not abbreviated, presumably because they are not included in [abbrv.jabref.org/journals](https://github.com/JabRef/abbrv.jabref.org/tree/main/journals)?

I can relabel these manually, but it would be helpful to be able to do this programatically with your package? Perhaps could `abbr2bib()` have an argument for the user to supply a dictionary of journal names:abbreviations?

Thanks for considering

**Comment by zoushucai** [comment]
@rmgpanw  Thank you for your suggestion. I have added this function to the `abbr2bib()` function, eg:

```R
require(journalabbr)
path = system.file("extdata", "testfile_1.bib", package = "journalabbr", mustWork = TRUE)
temptab = abbr2bib(file = path, outfile =  tempfile(fileext = ".bib"))

# add user csv
csvpath = system.file("extdata", "myabbr.csv", package = "journalabbr", mustWork = TRUE)
temptab1 = abbr2bib(file = path, outfile =  tempfile(fileext = ".bib"), addcsvpath = csvpath)

```

**Comment by rmgpanw** [comment]
Thanks for acting on this so quickly! Apologies I can't test this straightaway, but should be able to do so by the end of this week. I will post another comment after and hopefully close the issue :)
